// <auto-generated />
using System;
using LaptopRentalManagement.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LaptopRentalManagement.DAL.Migrations
{
    [DbContext(typeof(LaptopRentalDbContext))]
    [Migration("20250729100000_AddRentalFee")]
    partial class AddRentalFee
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LaptopCategory", b =>
                {
                    b.Property<int>("LaptopId").HasColumnType("int");
                    b.Property<int>("CategoryId").HasColumnType("int");
                    b.HasKey("LaptopId", "CategoryId").HasName("pk_LaptopCategory");
                    b.HasIndex("CategoryId");
                    b.ToTable("LaptopCategory");
                });

            modelBuilder.Entity("LaptopRentalManagement.DAL.Entities.Order", b =>
                {
                    b.Property<int>("OrderId").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));
                    b.Property<DateTime>("CreatedAt").ValueGeneratedOnAdd().HasColumnType("datetime2").HasDefaultValueSql("(sysutcdatetime())");
                    b.Property<decimal>("DepositAmount").HasColumnType("decimal(18,2)");
                    b.Property<DateOnly>("EndDate").HasColumnType("date");
                    b.Property<int>("LaptopId").HasColumnType("int");
                    b.Property<int>("OwnerId").HasColumnType("int");
                    b.Property<int?>("RenterId").HasColumnType("int");
                    b.Property<decimal>("RentalFee").HasColumnType("decimal(18,2)");
                    b.Property<DateOnly>("StartDate").HasColumnType("date");
                    b.Property<string>("Status").IsRequired().ValueGeneratedOnAdd().HasMaxLength(20).HasColumnType("nvarchar(20)").HasDefaultValue("Pending");
                    b.Property<decimal>("TotalCharge").HasColumnType("decimal(18, 2)");
                    b.Property<DateTime>("UpdatedAt").ValueGeneratedOnAdd().HasColumnType("datetime2").HasDefaultValueSql("(sysutcdatetime())");
                    b.Property<string>("ZaloPayTransactionId").HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.HasKey("OrderId").HasName("PK__Order__C3905BCFAA91515F");
                    b.HasIndex("LaptopId", name: "ix_Order_LaptopId");
                    b.HasIndex("OwnerId", name: "ix_Order_OwnerId");
                    b.HasIndex("RenterId", name: "ix_Order_RenterId");
                    b.HasIndex("StartDate", name: "ix_Order_StartDate");
                    b.ToTable("Order");
                });
#pragma warning restore 612, 618
        }
    }
}
